version: '3.9'
services:
  db:
    extends:
      file: docker-services.yml
      service: db
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    extends:
      file: docker-services.yml
      service: redis
  web:
    extends:
      file: docker-services.yml
      service: web
    ports:
      - "3000:3000"
    volumes:
      - webpersistent:/persistent
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started

volumes:
  webpersistent:
  pgdata:
